In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score
import seaborn as sb
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv(r'C:\Users\redwi\Downloads\Spring 20\CAP ML\Game.csv',error_bad_lines=False)

In [3]:
df.head()

ID       Date      Opponent  Is_Home_o r_Away  \
0   1   9/5/2015         Texas             Home    
1   2  9/12/2015      Virginia             Away    
2   3  9/19/2015  GeorgiaTec h             Home    
3   4  9/26/2015         UMass             Home    
4   5  10/3/2015       Clemson             Away    

  Is_Oppone nt_in_AP25 _Preseason   Media  Label  
0                            Out   1-NBC    Win   
1                            Out   4-ABC    Win   
2                             In   1-NBC    Win   
3                            Out   1-NBC    Win   
4                             In   4-ABC   Lose

In [4]:
df.columns

Index(['ID', 'Date', 'Opponent ', 'Is_Home_o r_Away',
       'Is_Oppone nt_in_AP25 _Preseason', 'Media', 'Label'],
      dtype='object')

In [5]:
print(df['Is_Home_o r_Away'].unique())

print(df['Is_Oppone nt_in_AP25 _Preseason'].unique())

print(df['Media'].unique())

print(df['Label'].unique())

['Home ' 'Away ']
['Out ' 'In ']
['1-NBC ' '4-ABC ' '3-FOX ' '2-ESPN ' '5-CBS ']
['Win ' 'Lose ']


In [6]:
df['Is_Home_o r_Away'] = df['Is_Home_o r_Away'].map({'Home ':1,'Away ':2}).astype(int)
df['Is_Oppone nt_in_AP25 _Preseason'] = df['Is_Oppone nt_in_AP25 _Preseason'].map({'Out ':0,'In ':1}).astype(int)
df['Media'] = df['Media'].map({'1-NBC ': 1, '4-ABC ':4, '3-FOX ':3, '2-ESPN ':2, '5-CBS ':5}).astype(int)
df['Label'] = df['Label'].map({'Win ': 1, 'Lose ':2}).astype(int)

In [7]:
df.head()

ID       Date      Opponent   Is_Home_o r_Away  \
0   1   9/5/2015         Texas                  1   
1   2  9/12/2015      Virginia                  2   
2   3  9/19/2015  GeorgiaTec h                  1   
3   4  9/26/2015         UMass                  1   
4   5  10/3/2015       Clemson                  2   

   Is_Oppone nt_in_AP25 _Preseason  Media  Label  
0                                0      1      1  
1                                0      4      1  
2                                1      1      1  
3                                0      1      1  
4                                1      4      2

In [8]:
np.array(df['Label'])

array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1,
       2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2])

In [9]:
train_df=df[df['ID']<=24]
test_df=df[df['ID']>24]
X_train=train_df.filter(['Is_Home_o r_Away','Is_Oppone nt_in_AP25 _Preseason', 'Media'])
Y_train=train_df['Label']

In [10]:
classifier_NB = GaussianNB()
classifier_NB.fit(X_train, Y_train)
print("Accuracy on training set: {:.3f}".format(classifier_NB.score(X_train, Y_train)))

Accuracy on training set: 0.708


In [11]:
X_test=test_df.filter(['Is_Home_o r_Away','Is_Oppone nt_in_AP25 _Preseason', 'Media'])
Y_test=test_df['Label']

In [14]:
print("Accuracy on test set: {:.3f}".format(classifier_NB.score(X_test, Y_test)))
Y_pred=classifier_NB.predict(X_test)
print(Y_pred)

Accuracy on test set: 0.833
[1 2 1 1 1 2 2 1 1 2 1 2]


In [16]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           1       1.00      0.78      0.88         9
           2       0.60      1.00      0.75         3

    accuracy                           0.83        12
   macro avg       0.80      0.89      0.81        12
weighted avg       0.90      0.83      0.84        12



In [17]:
confusion_matrix(Y_test, Y_pred)

array([[7, 2],
       [0, 3]], dtype=int64)

In [18]:
clf_ID3 = DecisionTreeClassifier(criterion='entropy',max_depth=15, random_state=0)

clf_ID3.fit(X_train, Y_train)

print("Accuracy on training set: {:.3f}".format(clf_ID3.score(X_train, Y_train)))

Accuracy on training set: 0.750


In [19]:
print("Accuracy on test set: {:.3f}".format(clf_ID3.score(X_test, Y_test)))
Y_pred=clf_ID3.predict(X_test)
print(Y_pred)

Accuracy on test set: 0.917
[1 1 1 1 1 1 1 1 1 2 1 2]


In [20]:
confusion_matrix(Y_test, Y_pred)

array([[9, 0],
       [1, 2]], dtype=int64)

In [21]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           1       0.90      1.00      0.95         9
           2       1.00      0.67      0.80         3

    accuracy                           0.92        12
   macro avg       0.95      0.83      0.87        12
weighted avg       0.92      0.92      0.91        12



In [26]:
df.to_csv(r'C:\Users\redwi\Downloads\Spring 20\CAP ML\game_df.csv')